# Generated by Django 5.2.9 on 2026-05-29 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название продукта')),
                ('unit', models.CharField(max_length=10, verbose_name='Единица измерения')),
                ('avg_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Средняя цена')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название рецепта')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('instructions', models.TextField(blank=True, verbose_name='Инструкция приготовления')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('is_published', models.BooleanField(choices=[(False, 'Черновик'), (True, 'Опубликовано')], default=False, verbose_name='Статус')),
                ('calories', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Калории (ккал)')),
                ('proteins', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Белки (г)')),
                ('fats', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Жиры (г)')),
                ('carbs', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Углеводы (г)')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='recipes_photos/%Y/%m/%d/', verbose_name='Изображение рецепта')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
                'ordering': ['-time_create'],
            },
        ),
        migrations.CreateModel(
            name='RecipeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('завтрак', 'завтрак'), ('ужин', 'ужин'), ('обед', 'обед'), ('десерты', 'десерты')], max_length=100, verbose_name='Название категории')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категория рецепта',
                'verbose_name_plural': 'Категории рецептов',
            },
        ),
        migrations.CreateModel(
            name='RecipeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(blank=True, verbose_name='Ссылка на видео')),
                ('cooking_tip', models.TextField(blank=True, verbose_name='Совет по приготовлению')),
                ('servings', models.PositiveSmallIntegerField(default=1, verbose_name='Порций')),
            ],
            options={
                'verbose_name': 'Деталь рецепта',
                'verbose_name_plural': 'Детали рецептов',
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Ингредиент рецепта',
                'verbose_name_plural': 'Ингредиенты рецептов',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Название тега')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
    ]
