# Generated by Django 5.2.9 on 2026-04-17 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='recipecategory',
            options={'verbose_name': 'Категория рецепта', 'verbose_name_plural': 'Категории рецептов'},
        ),
        migrations.AlterModelOptions(
            name='recipedetail',
            options={'verbose_name': 'Деталь рецепта', 'verbose_name_plural': 'Детали рецептов'},
        ),
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'verbose_name': 'Ингредиент рецепта', 'verbose_name_plural': 'Ингредиенты рецептов'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AlterField(
            model_name='product',
            name='avg_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Средняя цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(max_length=10, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='calories',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Калории (ккал)'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='carbs',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Углеводы (г)'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipes', to='Recipes.recipecategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='fats',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Жиры (г)'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(blank=True, verbose_name='Инструкция приготовления'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='is_published',
            field=models.BooleanField(choices=[(False, 'Черновик'), (True, 'Опубликовано')], default=False, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='proteins',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Белки (г)'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='Recipes.tag', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название рецепта'),
        ),
        migrations.AlterField(
            model_name='recipecategory',
            name='name',
            field=models.CharField(choices=[('завтрак', 'завтрак'), ('ужин', 'ужин'), ('обед', 'обед'), ('десерты', 'десерты')], max_length=100, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='recipedetail',
            name='recipe',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extra', to='Recipes.recipe', verbose_name='Рецепт'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in_recipes', to='Recipes.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='Recipes.recipe', verbose_name='Рецепт'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Название тега'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='URL'),
        ),
    ]
