# Generated by Django 5.2.9 on 2026-05-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0002_alter_product_options_alter_recipecategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='recipes_photos/%Y/%m/%d/', verbose_name='Изображение рецепта'),
        ),
    ]
